title: "Railsの練習帳"
summary: "Railsの学習をサポートする書籍です。難易度としては、Railsの基礎であるCRUDの動作を解説した「Railsの教科書」(https://tatsu-zine.com/books/rails-textbook)を終え、「Railsガイド」(https://railsguides.jp)をおおよそ学んだあとに読んでいただくことを想定しています。「パーフェクトRails」(https://gihyo.jp/book/2020/978-4-297-11462-6)に掲載されている基礎レベル文章程度の難易度にできればと考えています。"
topics: ["Rails", "Ruby"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - preface
  - ar_usefuls
  - ar_inverse_of
  - ar_transaction_lock
  - ar_sql_injection
  - ar_delegated_type
  - ar_processing_across_multiple_models
  - ruby_rails_references
  - rack_middleware_and_rack
  - remaining_variables
  - rails_idioms
  - ruby_idioms
  - ruby_argument_literals
  - ruby_rails_debugging
  - ruby_rails_debug_gem
  - ruby_rails_vscode
  - rails_rspec_workshop
  - rails_graphql_workshop
  - rails_rubocop_custom_cop
  - writing_sponsors

